### ISSUE TITLE
[Software]: PC1

### ISSUE THREAD

**Issue by MauricioMachadoFF** [UNB-PI2-Grupo3-BracoRobotico/Documentation#3]
# Descrição

Essa issue serve como épico para as tarefas que devem ser realizadas para o Ponto de Controle 1 relativo a software.

## Atividades/ Artefatos

- [x] Documento de Arquitetura
  - [x] #6 (@DaviMatheus)
  - [x] #7 (@savioc2)
  - [x] #8 (@MauricioMachadoFF)
  - [x] #9 (@fmaachadoo)
  - [x] #10(@SamuelCastro7 )
  - [x] #11(@PedroMoraes39)
  - [x] #12(@PedroMoraes39)
  - [x] #13 (@fernandes-natanael)
- [ ] Documento de Visão
  - [x] #14(@SamuelCastro7, @savioc2, @DaviMatheus )
  - [x] #15 (@savioc2)
 - [x] Documento de Requisitos
   - [x] #17(@DaviMatheus )
   - [x] #18 (@fmaachadoo @MauricioMachadoFF @fernandes-natanael @DaviMatheus @PedroMoraes39 )
   - [x] #19 (@MauricioMachadoFF)
